# Site settings
title: "Tim + Rachel"
description: |
    Sewickley, PA

    September 12, 2002
owner: Tim Macdonald
first_published: 2020
email: tsmacdonald@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.timchel.com" # the base hostname & protocol for your site

# Google analytics
google_analytics: "UA-160035647-1"

# Build settings
markdown: kramdown
